services:

  sales-api:
    image: underworld-sales-api:local
    build:
      context: .
      dockerfile: src/Services/Sales/UnderworldAPI.Sales.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SalesDb=Server=sqlserver,1433;Database=UnderworldDB;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;
      - AzureServiceBus__ConnectionString=
      - AzureServiceBus__TopicName=sales-events
    ports:
      - "5100:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  purchases-api:
    image: underworld-purchases-api:local
    build:
      context: .
      dockerfile: src/Services/Purchases/UnderworldAPI.Purchases.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PurchasesDb=Server=sqlserver,1433;Database=UnderworldDB;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;
      - AzureServiceBus__ConnectionString=
      - AzureServiceBus__TopicName=purchases-events
    ports:
      - "5200:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local