<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UnderworldAPI.Purchases.Application\UnderworldAPI.Purchases.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\UnderworldAPI.Shared.Infrastructure\UnderworldAPI.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection/" />
    <Folder Include="Messaging/" />
    <Folder Include="Migrations/" />
    <Folder Include="Persistence/" />
    <Folder Include="Persistence/Configurations/" />
    <Folder Include="Persistence/Migrations/" />
    <Folder Include="Persistence/Repositories/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
