<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UnderworldAPI.Purchases.Domain\UnderworldAPI.Purchases.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\UnderworldAPI.Shared.Domain\UnderworldAPI.Shared.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors/" />
    <Folder Include="DependencyInjection/" />
    <Folder Include="DTOs/" />
    <Folder Include="Mappings/" />
    <Folder Include="PurchaseOrders/Commands/" />
    <Folder Include="PurchaseOrders/Commands/CreatePurchaseOrder/" />
    <Folder Include="PurchaseOrders/Commands/DeletePurchaseOrder/" />
    <Folder Include="PurchaseOrders/Commands/UpdatePurchaseOrder/" />
    <Folder Include="PurchaseOrders/Queries/GetAllPurchaseOrders/" />
    <Folder Include="PurchaseOrders/Queries/GetPurchaseOrderById/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
