<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnderworldAPI.Sales.Application\UnderworldAPI.Sales.Application.csproj" />
    <ProjectReference Include="..\UnderworldAPI.Sales.Infrastructure\UnderworldAPI.Sales.Infrastructure.csproj" />
  </ItemGroup>

</Project>
