<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UnderworldAPI.Sales.Domain\UnderworldAPI.Sales.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\UnderworldAPI.Shared.Domain\UnderworldAPI.Shared.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

   <!-- Permite que el proyecto de tests vea los tipos internal -->
  <ItemGroup>
    <InternalsVisibleTo Include="UnderworldAPI.Sales.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions/" />
    <Folder Include="Behaviors/" />
    <Folder Include="DependencyInjection/" />
    <Folder Include="DTOs/" />
    <Folder Include="Mappings/" />
    <Folder Include="Orders/Commands/CreateOrder/" />
    <Folder Include="Orders/Commands/DeleteOrder/" />
    <Folder Include="Orders/Queries/" />
    <Folder Include="Orders/Queries/GetAllOrders/" />
    <Folder Include="Orders/Queries/GetOrderById/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
